[logger]

# Level of logging: 'error', 'warning', 'info', 'debug'.
level = "info"

[client]

# If false, will attempt to open the browser automatically.
showSidebarNavigation = true

# Controls whether uncaught app exceptions are displayed in the browser. By
# default, this is set to True and Streamlit displays app exceptions and
# associated tracebacks in the browser.
showErrorDetails = true

[server]

# List of folders that should not be watched for changes. This impacts both
# "Run on Save" and @st.cache.
folderWatchBlacklist = ['']

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas,
# this should be set to the same value across all replicas to ensure they all
# share the same secret.
cookieSecret = "a-random-key-appears-here"

# If false, will attempt to open the browser automatically.
headless = true

# Automatically rerun script when the file is modified on disk.
runOnSave = false

# The address where the server will listen for client and server connections.
address = "localhost"

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Enables support for Cross-Origin Request Sharing (CORS) protection, for added security.
enableCORS = true

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
enableXsrfProtection = false

# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false
