GEMINI_API_KEY = "AIzaSyDg7geHMlRnqnldmzcXPzqV5ssWUCzrtAw"
SUPABASE_URL = "https://mzwrldtbkploewvlxfmb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16d3JsZHRia3Bsb2V3dmx4Zm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMDc3MzksImV4cCI6MjA3OTg4MzczOX0.sQ3Olnjg5Ho6HsDxJb2kcR0JizTB2xLdFGNNgMO_PAM"